/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KidsCourseRouteImport } from './routes/kids-course'
import { Route as IndexRouteImport } from './routes/index'

const KidsCourseRoute = KidsCourseRouteImport.update({
  id: '/kids-course',
  path: '/kids-course',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kids-course': typeof KidsCourseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kids-course': typeof KidsCourseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kids-course': typeof KidsCourseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kids-course'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kids-course'
  id: '__root__' | '/' | '/kids-course'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KidsCourseRoute: typeof KidsCourseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kids-course': {
      id: '/kids-course'
      path: '/kids-course'
      fullPath: '/kids-course'
      preLoaderRoute: typeof KidsCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KidsCourseRoute: KidsCourseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
